# Generated by Django 2.2.6 on 2019-10-31 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rereceta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receta',
            options={'verbose_name': 'Receta', 'verbose_name_plural': 'Recetas'},
        ),
        migrations.AlterField(
            model_name='image',
            name='imagen',
            field=models.ImageField(default=None, upload_to='recetas'),
        ),
    ]
