# Generated by Django 2.2.6 on 2019-11-01 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rereceta', '0003_auto_20191030_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Integrantes',
                'verbose_name': 'Integrante',
            },
        ),
    ]
